[package]
name = "cursive_table_view"
version = "0.11.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]
description = "A basic table view implementation for cursive."
repository = "https://github.com/BonsaiDen/cursive_table_view.git"
readme = "README.md"
keywords = ["cursive", "ncurses", "TUI", "UI", "table"]
categories = ["command-line-interface", "gui"]
license = "MIT/Apache-2.0"

[dependencies]
cursive = { version = "0.14", default-features = false }

[dev-dependencies]
cursive = "0.14"
rand = "0.7"
